# Generated by Django 5.0.3 on 2026-04-09 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('source_type', models.CharField(max_length=10)),
                ('source_id', models.CharField(max_length=100)),
                ('chunk_index', models.IntegerField(default=0)),
                ('vector_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('total_chunks', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(default='document', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WebSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('total_chunks', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(default='web', max_length=10)),
            ],
        ),
    ]
